feat: full version of upback

diff --git a/lab4/upback b/lab4/upback
--- a/lab4/upback
+++ b/lab4/upback
@@ -33,4 +33,45 @@ for DIR in /home/user/*; do
 	fi
 done
 
-echo $BACKUP_DIR
+if ! [[ -d $BACKUP_DIR ]]; then
+	echo "Error: no backups found"
+	exit 1
+fi
+
+COUNT=0
+for FILE in $BACKUP_DIR/*; do
+	FILENAME=$(echo "$FILE" | grep -E -o "[^\/]*$")
+	
+	# if file has YY-MM-DD in its name
+	if [[ "$FILENAME" =~ .*\.[1-9][0-9]{1,3}-[0-9]{2}-[0-9]{2} ]]; then
+		ORIGIN_NAME=${FILENAME%.*}
+
+		# if YY-MM-DD is not original name and file exists then skip it
+		if [[ $ORIGIN_NAME != "" ]] && [[ -f "$BACKUP_DIR/$ORIGIN_NAME" ]]; then
+			continue
+		fi
+	fi
+
+	cp "$FILE" "$RESTORE_DIR" &&
+	{
+		COUNT=$(($COUNT+1))
+	}
+done
+
+echo "$COUNT files restored from backup"
+exit 0
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
